config/routes.rb
Rails.application.routes.draw do

  #ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

    #管理者用
  #URL /admin/sign_in ...
  devise_for :admins, contollers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
  end


  #顧客用
  #URL customers/sign_in ...
  scope module: :public do
    root 'homes#top'
    devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
    resources :customers, only: [:show, :edit, :destroy] do
      resource :relationships, only: [:create, :destroy]
        get 'followers' => 'relationships/followers', as: 'followers'
        get 'followings' => 'relationships/followings', as: 'followings'
    end
    resources :recipes, only: [:new, :index, :show, :create, :destroy] do
      resources :ingredients, only: [:create, :edit, :destroy]
      resources :cooking_process, only: [:create, :edit, :destroy]
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/cooking_process.rb
class CookingProcess < ApplicationRecord
  
  has_one_attached :image
  belongs_to :recipe
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :nickname, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :email, uniqueness: true

  def self.guest
    find_or_create_by(nickname: 'guestuser' , email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      # binding.pry
      customer.nickname = "guestuser"
    end
  end

  # def get_profile_image
  #   unless profile_image.attached?
  #     file_path = Rails.root.join('app/assets/images/no_image.jpeg')
  #     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  #   end
  #   profile_image.variant(resize_to_limit: [width, height]).processed
  # end

  def follow(customer)
    relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :customer
  has_many :ingredients, dependent: :destroy
  has_many :cooking_process, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :ingredients, :cooking_process
  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io:File.open(file_path), filename:'default-image.jpeg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :recipe
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #devise利用の機能が使われる前にconfigure_permitted_parametersメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    recipes_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  #devise_parameter_sanitizer.permitメソッドを使うことでユーザー登録の際に、ユーザー名のデータ操作を許可
  protected
  #privateは記述したコントローラー内でしか参照できない
  #protectedは呼び出された他のコントローラーからも参照できる
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/ingredients_helper.rb
module Admin::IngredientsHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/admin/relationships_helper.rb
module Admin::RelationshipsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!--<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>-->
<!--  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<!--<%# end %>-->

<!--<#%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>-->
<!--  <#%= link_to "Forgot your password?", new_password_path(resource_name) %><br />-->
<!--<#% end %>-->

<!--<#%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>-->
<!--  <#%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />-->
<!--<#% end %>-->

<!--<#%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>-->
<!--  <#%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />-->
<!--<#% end %>-->

<!--<#%- if devise_mapping.omniauthable? %>-->
<!--  <#%- resource_class.omniauth_providers.each do |provider| %>-->
<!--    <#%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />-->
<!--  <#% end %>-->
<!--<#% end %>-->

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/">俺のレシピが一番ウマい！</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <!--<li class="nav-item">-->
            <!--  <#%= link_to "ユーザー一覧", public_customers_path, class: 'nav-link text-dark' %>-->
            <!--</li>-->
            <li class="nav-item">
              <%= link_to 'ホーム', recipes_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item">
              <%= link_to 'レシピ新規投稿', new_recipe_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item">
              <%= link_to 'マイページ', customer_path(current_customer.id), class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item">
              <%= button_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "ユーザー一覧", admin_customers_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark'%>
            </li>
          <% else %>
            <!--<li class="nav-item">-->
            <!--  <%#= link_to "ホーム", public_path, class: 'nav-link text-dark' %>-->
            <!--</li>-->
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrenoRecipeGaIchibanumai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>